version: "2.4"

services:
  mysql:
    image: mysql:5.6
    hostname: mysqldb
    domainname: openair4G.eur
    container_name: mysqldb
    environment: # shell variables
      - MYSQL_ROOT_PASSWORD=linux
      - MYSQL_DATABASE=oai_db
    networks:
      oai:
        ipv4_address: 192.188.2.10
  oaihss:
    build: hss
    hostname: hss
    domainname: openair4G.eur
    container_name: oaihss
    privileged: true
    depends_on:
      - mysql
    networks:
      oai:
        ipv4_address: 192.188.2.3
  oaimme:
    build: mme
    hostname: mme
    domainname: openair4G
    container_name: oaimme
    privileged: true
    depends_on: 
      - oaihss
    networks:
      oai:
        ipv4_address: 192.188.2.2      
networks:
  oai:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.188.2.0/24